Flexibility to specify a config file without a separate config map
renovatebot/helm-charts pull request #116
Opened 2021-05-05 16:02 UTC by tiagoposse

Add renovate.configFile and env keywords to values.

These changes allow injecting a config file via a init container (fetches the required token from an external secrets manager and injects a template into config.json) in a simple way that still keeps the requirement for config or configFile.

2021-05-05 16:06 UTC, viceice approved these changes

2021-05-06 04:02 UTC, JamieMagee commented
Overall looks okay. Just needs the docs to be regenerated.

Can I ask about your use case: Is it not possible to store the entire config as an existing secret? Is there something about your configuration that needs to be frequently updated or generated at runtime? Just curious how people are using this chart.

2021-05-06 04:19 UTC, viceice commented
@JamieMagee i think the major use case is to generate some short living access token, eg when using custom github app for renovate. 😉

2021-05-06 05:03 UTC, viceice requested changes
needs lint fix:

```diff
diff --git a/charts/renovate/README.md b/charts/renovate/README.md
index 828f507..3531ca7 100644
--- a/charts/renovate/README.md
+++ b/charts/renovate/README.md
@@ -47,6 +47,7 @@ The following table lists the configurable parameters of the chart and the defau
 | cronjob.labels | object | `{}` |  |
 | cronjob.schedule | string | `"0 1 * * *"` |  |
 | cronjob.successfulJobsHistoryLimit | string | `""` |  |
+| env | object | `{}` |  |
 | envFrom | list | `[]` |  |
 | existingSecret | string | `""` |  |
 | image.pullPolicy | string | `"IfNotPresent"` |  |
@@ -60,6 +61,7 @@ The following table lists the configurable parameters of the chart and the defau
 | redis.nameOverride | string | `"redis"` |  |
 | redis.usePassword | bool | `false` |  |
 | renovate.config | string | `""` |  |
+| renovate.configFile | string | `""` |  |
 | resources | object | `{}` |  |
 | secrets | object | `{}` |  |
 | serviceAccount.annotations | object | `{}` |  |
```

2021-05-06 05:48 UTC, tiagoposse commented
There are two use cases, the first covered by @viceice, the second is related to storing the token in AWS SecretsManager/Vault/Google Secrets Manager and not giving developers access permission to it (it would allow them to impersonate another entity in gitlab), while still allowing those same devs to change some configs of renovate (e.g. the log level) without messing with the secret. Hope this clears it up :)

2021-05-06 05:58 UTC, viceice commented
I see, it's currently not possible to use a `config.js` file, with that you could required additional dynamically generated files.

2021-05-06 06:41 UTC, tiagoposse commented
I've realised there was a mistake I didn't test correctly, I pushed a change. the volume and volumeMounts section need to be adapted .Values.renovate.config is not passed. Considering so, maybe it's worth having a better name for configFile, that indicates this is supposed to be passed in a way completely external to the chart?

2021-05-08 04:11 UTC, JamieMagee commented
What about `existingConfigFile`? It's in line with `existingSecret`.

2021-05-12 09:49 UTC, tiagoposse commented
Updates done and the commits were squashed. If it looks good, I'm happy with the result and should be okay to merge.

2021-05-12 12:36 UTC, viceice commented
@tiagoposse Please do not squash your commits, we will do a squash merge anyways, so your pr only needs to be up-to-date 😉

2021-05-12 12:39 UTC, viceice commented on charts/renovate/README.md
> +| renovate.externalConfigFile | string | `"Bring your own config file, using your own mount"` |  |
Why `externalConfigFile` ? Didn't we suggest `existingConfigFile` ? 🤔

2021-05-17 08:15 UTC, tiagoposse commented on charts/renovate/README.md
> +| renovate.externalConfigFile | string | `"Bring your own config file, using your own mount"` |  |
You did, my bad here. Corrected

2021-05-17 08:36 UTC, viceice approved these changes
LGTM

@JamieMagee Can you please check this too

2021-05-17 08:36 UTC, viceice commented on charts/renovate/templates/configmap.yaml
> +{{- end }}
```suggestion
{{- end }}

```

newline at end

2021-05-17 08:39 UTC, viceice requested changes
needs some changes in readme:
```diff
diff --git a/charts/renovate/README.md b/charts/renovate/README.md
+ curl --silent --show-error --fail --location --output /tmp/helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz
index e29a8ec..a641f54 100644
+ tar -xf /tmp/helm-docs.tar.gz helm-docs
--- a/charts/renovate/README.md
+++ b/charts/renovate/README.md
@@ -61,7 +61,7 @@ The following table lists the configurable parameters of the chart and the defau
 | redis.nameOverride | string | `"redis"` |  |
+ ./helm-docs
time="2021-05-17T08:37:04Z" level=info msg="Found Chart directories [charts/renovate]"
 | redis.usePassword | bool | `false` |  |
 | renovate.config | string | `""` |  |
-| renovate.existingConfigFile | string | `"Bring your own config file, using your own mount"` |  |
+| renovate.existingConfigFile | string | `""` |  |
 | resources | object | `{}` |  |
 | secrets | object | `{}` |  |
 | serviceAccount.annotations | object | `{}` |  |
time="2021-05-17T08:37:04Z" level=info msg="Generating README Documentation for chart /home/runner/work/helm-charts/helm-charts/charts/renovate"
+ git diff --exit-code
```

2021-05-25 19:49 UTC, viceice approved these changes

2021-05-25 19:49 UTC, merged