feat: allow additional volumes
renovatebot/helm-charts pull request #127
Opened 2021-05-29 15:08 UTC by r-mironov

Hi, this PR closes https://github.com/renovatebot/helm-charts/issues/120 

There are some new features via helm values: 
- add extra(additional) configmaps
- add extra volumes
- add extra volumeMounts
- 
You can combine them to provide custom files(configs) to renovate's container

2021-06-17 09:04 UTC, viceice approved these changes

2021-07-19 10:13 UTC, viceice commented
needs deconflicting

2021-07-21 11:25 UTC, r-mironov commented
resolved

2021-07-21 14:11 UTC, viceice requested changes
Please revert non required indention changes

2021-07-21 18:40 UTC, r-mironov commented
> Please revert non required indention changes

Done, please check it

2021-07-29 09:04 UTC, viceice approved these changes

2021-08-03 09:24 UTC, viceice requested changes

2021-08-03 09:24 UTC, viceice commented on charts/renovate/values.yaml
> +# A generated configMap name is: "renovate.fullname" + "extra" + name(below) e.g. renovate-netrc-config
```suggestion
# -- A generated configMap name is: "renovate.fullname" + "extra" + name(below) e.g. renovate-netrc-config
```

Show in readme

2021-08-03 09:24 UTC, viceice commented on charts/renovate/values.yaml
> +# Additional volumes to the pod
```suggestion
# -- Additional volumes to the pod
```

2021-08-03 09:24 UTC, viceice commented on charts/renovate/values.yaml
> +# Additional volumeMounts to the container
```suggestion
# -- Additional volumeMounts to the container
```

2021-08-04 15:31 UTC, r-mironov commented on charts/renovate/values.yaml
> +# A generated configMap name is: "renovate.fullname" + "extra" + name(below) e.g. renovate-netrc-config
Helm-docs can't correct parse:
```
# Additional configmaps
# -- A generated configMap name is: "renovate.fullname" + "extra" + name(below) e.g. renovate-netrc-config
```
It transforms to:
```
| extraConfigmaps | list | `[]` | |
| extraVolumeMounts | list | `[]` | Additional volumeMounts to the container |
| extraVolumes | list | `[]` | Additional volumes to the pod |
```
So I combined 62-63 lines, looks pretty good

2021-08-05 07:28 UTC, viceice approved these changes

2021-08-05 07:33 UTC, viceice commented on charts/renovate/Chart.yaml
> +version: '25.56.7+1'
This will only release the chart to github release, chart repo won't updated. So you need to wait for next official renovate release after merge

2021-08-05 07:43 UTC, merged