feat(exit-on-errors): Add an option to enable/disable the usage of `set -e` inside args of cronjob
renovatebot/helm-charts pull request #1299
Opened 2024-05-07 09:09 UTC by Lowaiz

I also added a quick update of the README template, to be able to run helm-docs without errors, and without editing the README manually

2024-05-07 15:55 UTC, viceice commented on charts/renovate/README.md.gotmpl
> +Allows you to reference values using `"{{ "{{ .Values.someValue }}" }}"` in your config
please do this in a separate PR

2024-05-07 16:17 UTC, Lowaiz commented on charts/renovate/README.md.gotmpl
> +Allows you to reference values using `"{{ "{{ .Values.someValue }}" }}"` in your config
Ok

2024-05-07 16:19 UTC, Lowaiz commented on charts/renovate/README.md.gotmpl
> +Allows you to reference values using `"{{ "{{ .Values.someValue }}" }}"` in your config
Done

2024-05-07 16:26 UTC, Lowaiz commented
We are running Renovate on few thousand repositories on a self-hosted Gitlab, and time to time, Gitlab produce a 429 return status code when POST/PUT a merge request, making a Renovate returning a non-zero code.

We don't really mind these fails, as it appears 2 or 3 times per run and renovate run twice a day.
But the fail status of the Kubernetes jobs make it to re run instantly, spamming the ressources.
I proposed to just add an option to let people decide whenever they want to ignore renovate exit code.
I may also propose to have an option to override the whole args part, but let's starts with an easier option to use.

2024-05-08 07:59 UTC, viceice commented
> We are running Renovate on few thousand repositories on a self-hosted Gitlab, and time to time, Gitlab produce a 429 return status code when POST/PUT a merge request, making a Renovate returning a non-zero code.
> 
> We don't really mind these fails, as it appears 2 or 3 times per run and renovate run twice a day. But the fail status of the Kubernetes jobs make it to re run instantly, spamming the ressources, without repeating the error on the same repo/branch. I proposed to just add an option to let people decide whenever they want to ignore renovate exit code. I may also propose to have an option to override the whole args part, but let's starts with an easier option to use.

Please update the PR description

2024-05-08 08:00 UTC, viceice commented
and run `helm-docs` to update the readme with the new option

2024-05-08 08:06 UTC, viceice requested changes
I prefer to implement full overriding of command and args instead of such an option. Can you implement this?

2024-05-10 07:55 UTC, closed without merging