feat: add dind sidecar option (#91)
renovatebot/helm-charts pull request #131
Opened 2021-06-18 10:35 UTC by lorisepita

Hi, this PR closes #91

There are some new features via helm values:

    enable dind container
    change the used dind docker image

This will allow the user to enable the `binarySource=docker` option.

2021-06-18 10:44 UTC, viceice requested changes

2021-06-18 10:44 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
>                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
if dind is use we should use the slim image tag. can you add some conditional for it? The slim image is a lot smaller! so pull will be faster.

2021-06-18 10:44 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                - name: DOCKER_TLS_CERTDIR
I like to see TLS enabled, can be done via shared temp volume, see https://gitlab.com/renovate-bot/renovate-runner/-/blob/main/templates/renovate-dind.gitlab-ci.yml for working sample for gitlab pipeline

2021-06-18 10:44 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                  renovate
We need to wait until docker is started, otherwise we can get a race condition.

2021-06-18 10:45 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
>                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
The slim image is also already configured for `binarySource=docker`

2021-06-18 13:12 UTC, lorisepita commented on charts/renovate/templates/cronjob.yaml
>                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
Should I add it as a recommendation in the notes or should I block the deploy when slim is not provided ? I am asking because I guess people could be using a custom image based on slim in which case they would be stuck because of the tag.

2021-06-18 13:53 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
>                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
Not sure how to best solve it. maybe conditional slim suffix, which is enabled by `dind.slim.enabled = true` ?

So if you need own tags, you can simply disable that

2021-06-21 08:54 UTC, lorisepita commented on charts/renovate/templates/cronjob.yaml
>                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
Well I guess the best way for me would be to show a warning in the notes during deployment saying that the slim image should be used when the tag is not `slim` and dind is enabled. That would let people use custom image as well as raising awareness to the right image to use.

But I could also add the option you recommended in the values I you think it is the best way to solve it.

2021-06-22 09:57 UTC, lorisepita commented
Hello, I added the changes you requested :)

2021-06-22 10:05 UTC, viceice commented on charts/renovate/templates/_helpers.tpl
> +{{- if and .Values.dind.enabled .Values.dind.slim.enabled (not (eq .Values.image.tag "slim")) -}}
The tag can be `slim` or it can have a version prefix, eg: `25-slim`, `25.49-slim` or `25.49.1-slim`

2021-06-22 15:49 UTC, viceice reviewed
@JamieMagee What do you think about this?

2021-06-22 15:49 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                  touch /tmp/docker-started
Is it safe to assume docker is fully started?

2021-06-22 16:55 UTC, lorisepita commented on charts/renovate/templates/cronjob.yaml
> +                  touch /tmp/docker-started
I am changing this but will only be able to commit it tomorrow !

2021-06-24 14:23 UTC, viceice approved these changes

2021-06-24 16:19 UTC, JamieMagee commented on charts/renovate/values.yaml
> +    repository: docker
Small nit

```suggestion
    repository: docker.io/library/docker
```

2021-06-24 16:29 UTC, JamieMagee commented on charts/renovate/values.yaml
> +    tag: 19.03.14-dind
Why 19.x over 20.x?

2021-06-24 16:29 UTC, JamieMagee commented
Sorry for the delay in review, just 2 very small comments.

Semi-related, @viceice Do we have an issue for tracking rootless work?

2021-06-24 16:29 UTC, JamieMagee approved these changes

2021-06-24 16:34 UTC, viceice commented
Not I'm aware of.

2021-06-28 14:11 UTC, lorisepita commented on charts/renovate/values.yaml
> +    repository: docker
Changed

2021-06-28 14:11 UTC, lorisepita commented on charts/renovate/values.yaml
> +    tag: 19.03.14-dind
No particular reason, changed it

2021-06-29 01:06 UTC, JamieMagee approved these changes

2021-06-29 07:21 UTC, viceice commented on charts/renovate/values.yaml
> +    tag: 19.03.14-dind
I know about some issues about docker v20 and kubernetes, see containerd/containerd#4837, it's fixed since containerd v1.4.4

2021-06-29 07:27 UTC, viceice commented
> Sorry for the delay in review, just 2 very small comments.
> 
> Semi-related, @viceice Do we have an issue for tracking rootless work?

@JamieMagee  I've tried to run dind in renovate directly but couldn't solve uid issues renovatebot/docker-renovate#224

2021-06-29 07:30 UTC, viceice commented on charts/renovate/README.md
> +| dind.enabled | bool | `false` |  |
Please add a docker dind / renovate slim section. So users are some more aware of the dind / slim usage.

2021-06-29 08:55 UTC, lorisepita commented on charts/renovate/README.md
> +| dind.enabled | bool | `false` |  |
Do you want me to move ` | dind.slim.enabled | bool | `true` |  |` from line 54 to line 52 ?

2021-06-29 08:57 UTC, lorisepita commented on charts/renovate/README.md
> +| dind.enabled | bool | `false` |  |
It es referenced at line 54 of this file ! I just generated the file using the provided script in the .github folder of this repo. Do you want me to add something else ?

2021-06-29 11:16 UTC, viceice commented
@lorisepita My idea wasn't clear enough. I like to have a new markdown section below here:

https://github.com/renovatebot/helm-charts/blob/67bf2970d8638a3249d0a36551b70a804fa72331/charts/renovate/README.md.gotmpl#L39

There should be a small description how to use the chart with dind and renovate slim.

2021-06-29 11:19 UTC, viceice commented
@JamieMagee  What do you think about adding the `-slim` suffix automaticall if `dind.enabled=true` and  `dind.slim.enabled=true` 

So for normal users it will automatically use the slim image when dind is activated. And we simply add a description how to disable auto slim tags when a custom image is required.

2021-06-29 15:01 UTC, lorisepita commented
@viceice Yes I can do that ! I will add it after knowing if I have to implement the idea you posted in the last comment because it will have an impact on the content :)

2021-07-15 15:10 UTC, viceice reviewed
Please add the `-slim` suffix automatically if dind.enabled=true and dind.slim.enabled=true instead of throwing a warning / error

2021-07-16 10:04 UTC, loristo commented
Done :)

2021-07-16 10:42 UTC, viceice approved these changes

2021-07-16 10:50 UTC, viceice commented
Can you add a new test to https://github.com/renovatebot/helm-charts/tree/main/charts/renovate/ci so we can test the installation on ci?

You can simply copy the default `ci-values.yaml` and enable dind.

2021-07-19 08:40 UTC, loristo commented
Done !

2021-07-19 08:43 UTC, viceice approved these changes

2021-07-19 10:12 UTC, merged