docs: recommend redis when users want to use a cache for renovate
renovatebot/helm-charts pull request #1799
Opened 2024-09-21 04:38 UTC by tibeer

The disk cache is very likely to pile up quickly. This will
prevent the Job to be executed once the PersistentVolume is full.
More information can be found here:
https://github.com/renovatebot/renovate/discussions/30525

Signed-off-by: Tim Beermann <tibeer@outlook.de>

2024-12-05 08:33 UTC, viceice requested changes

2024-12-05 08:33 UTC, viceice commented on charts/renovate/values.yaml
> +  # Take a look at https://github.com/renovatebot/renovate/discussions/30525 for more information.
This should also be in the generated readme. You should also mention that using SQLite cache is also a good alternative

2024-12-06 07:17 UTC, tibeer commented on charts/renovate/values.yaml
> +  # Take a look at https://github.com/renovatebot/renovate/discussions/30525 for more information.
@viceice Thanks for the feedback. I pushed the changes, tell me if this is what was desired :)

2024-12-09 21:08 UTC, viceice approved these changes

2024-12-09 21:08 UTC, viceice commented on charts/renovate/values.yaml
> +  # Take a look at https://github.com/renovatebot/renovate/discussions/30525 for more information.
please use the re-request review button next time instead of comment

2024-12-10 08:38 UTC, tibeer commented
Something got completly messed up during interactive rebase. I created a new, clean pull request: https://github.com/renovatebot/helm-charts/pull/2099

2024-12-10 08:38 UTC, closed without merging

2024-12-10 18:38 UTC, viceice commented
you could simply force push to fix