activeDeadlineSeconds and commonLabels support
renovatebot/helm-charts pull request #249
Opened 2022-10-14 10:17 UTC by kvanzuijlen

2022-10-14 10:24 UTC, viceice requested changes
add doc lines to values and update readme

2022-10-14 10:25 UTC, kvanzuijlen commented
Will add them to the values.yaml as well

2022-10-14 10:27 UTC, kvanzuijlen commented
Thx for your quick response @viceice, hope these changes are sufficient!

2022-10-14 10:28 UTC, viceice reviewed
don't require review if it's not fully done to reduce noise.

2022-10-14 10:53 UTC, kvanzuijlen commented
@viceice should be fully done right now, or am I still missing something? I don't really see why the lint check is failing.

2022-10-14 14:47 UTC, viceice commented
@JamieMagee do you know the error?

2022-10-14 14:57 UTC, kvanzuijlen commented on charts/renovate/templates/_helpers.tpl
> +{{ .Values.global.commonLabels | toYaml }}
I was just thinking the same thing, added them and the issue got solved (locally) after first reproducing the issue. Thx for your help @viceice

2022-10-17 11:45 UTC, viceice approved these changes

2022-10-18 07:16 UTC, viceice approved these changes

2022-10-20 06:35 UTC, merged