added overrideCommand value to cronjob template
renovatebot/helm-charts pull request #251
Opened 2022-10-19 23:34 UTC by rushrs

2022-10-20 06:33 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                {{- if .Values.cronjob.overrideCommand }}
instead of override the full command you should add an optional pre command, which will be executed before renovate.

2022-10-20 07:41 UTC, rushrs commented on charts/renovate/templates/cronjob.yaml
> +                {{- if .Values.cronjob.overrideCommand }}
Thanks for the quick code check. I have tried postStart lifecyle hooks but there is no guarantee that the postStart handler is called before the container's entrypoint is called.

To my understanding this is a pre-command, as the command is only ever overriden if either (or both) of  `.Values.dind.enabled` `.Values.cronjob.overrideCommand ` have been set. In those 3 scenarios the command called last is always `renovate` as seen on [line 82](https://github.com/renovatebot/helm-charts/pull/251/files#diff-f5e736815cf5032843de82fa404f0c12eb978ca469866588cf075fcafd96f93dR82). So the behaviour remains the same with any of the 3 scenarios.

Scenario 1: `.Values.cronjob.overrideCommand ` set
```
              command: ["/bin/bash", "-c"]
              args:
                - |
                  source /common/renovate.env
                  renovate
```

Scenario 2: `.Values.dind.enabled`   set
```
              command: ["/bin/bash", "-c"]
              args:
                - |
                  trap "touch /tmp/main-terminated" EXIT
                  while true; do if [[ -f "/tmp/dind-started" ]]; then break; fi; sleep 1; done
                  renovate
```

Scenario 3: `.Values.dind.enabled` `.Values.cronjob.overrideCommand ` both set
```
              command: ["/bin/bash", "-c"]
              args:
                - |
                  trap "touch /tmp/main-terminated" EXIT
                  while true; do if [[ -f "/tmp/dind-started" ]]; then break; fi; sleep 1; done
                  source /common/renovate.env
                  renovate
```

in a case where neither are set the default command for the image is `renovate` from what i've seen in the [Dockerfile](https://github.com/renovatebot/docker-renovate/blob/main/Dockerfile#L61)

2022-10-20 15:13 UTC, rushrs commented on charts/renovate/templates/cronjob.yaml
> +                {{- if .Values.cronjob.overrideCommand }}
I can rename the values in the values file and the cronjob to perhaps make what it does clearer

2022-10-21 09:53 UTC, viceice reviewed
do you still need this?

2022-10-21 09:53 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                {{- if .Values.cronjob.overrideCommand }}
yes, please rename to something like `preCommand`.

2022-10-21 10:22 UTC, rushrs commented
> do you still need this?

I switched to the config method you outlined in #248 and got it working that way.  but can see how this could be useful for other scenarios as the code is basically written

2022-10-27 13:39 UTC, rushrs commented
@viceice any updated on getting this merged in?

2022-10-27 15:46 UTC, viceice approved these changes

2022-10-27 15:52 UTC, viceice requested changes
No, the readme changes need to be commited, so revert your last commit

2022-10-27 16:06 UTC, rushrs commented
added it back

2022-10-27 16:13 UTC, viceice approved these changes

2022-10-27 16:30 UTC, merged