Added tpl to enable templated config values
renovatebot/helm-charts pull request #267
Opened 2023-01-04 11:01 UTC by kvanzuijlen

We use [helm secrets](https://github.com/jkroepke/helm-secrets) to encrypt configuration values like credentials. To reference these it would be nice to be able to reference these in the configuration without creating a custom configmap. To allow for this the tpl function has been added in this PR.

2023-01-04 16:11 UTC, viceice reviewed
What are the side effects? Breaking change?

2023-01-04 18:34 UTC, kvanzuijlen commented
Hi @viceice,

It could be breaking, but I think it's _higly_ unlikely. It would be breaking in the case that someone out there has the following  in their renovate configuration:
```
"someKey": "{{anyValue}}"
```
or
```
"someKey": "{{anyValue"
```

If you can think of a valid configuration key that would likely have such a value my suggestion would be to change it to a conditional option (add a key to the values.yaml called `configEnableTpl` or something like that).

For configurations not containing `{{` the config will still work the exact same, although it might be unnoticeably slower.

Please let me know what your preferred solution would be, either one should work for us and anyone having the same requirements as us in the future.

2023-01-04 18:49 UTC, viceice commented
renovate template files can contain handlebar token

2023-01-04 18:50 UTC, viceice commented
https://docs.renovatebot.com/templates/

2023-01-04 19:04 UTC, kvanzuijlen commented
Ofcourse... I didn't think about that, sorry. I think it's either back to the drawing board or making it clear in the documentation that with `configEnableHelmTpl` set to true you have to escape renovate templates like:
`"{{"{{depName}}"}}"` (wich would result in `"{{depName}}"` in the config.json).

Using `configEnableHelmTpl` would make this a useful feature to include imo, but it would add an extra section to the Helm chart documentation. I think the benefit will outweigh this drawback, since this feature would probably only be used consciously.

Can you give me a go ahead to implement `configEnableHelmTpl`, or would you like to see another solution (I can't think of one from the top of my head)?

2023-01-04 19:45 UTC, viceice requested changes
go ahead

2023-01-05 14:02 UTC, viceice commented on charts/renovate/values.yaml
> +  # "key": "{{ "{{depName}}" }}"
Can you please add a new section with this content to the readme, so it's more visible?

2023-01-05 14:14 UTC, kvanzuijlen commented on charts/renovate/values.yaml
> +  # "key": "{{ "{{depName}}" }}"
Should I keep it here as well?

2023-01-05 14:49 UTC, viceice commented on charts/renovate/values.yaml
> +  # "key": "{{ "{{depName}}" }}"
No, i think readme is enough

2023-01-06 08:57 UTC, viceice commented on charts/renovate/README.md.gotmpl
> +## renovate.configEnableHelmTpl
```suggestion
## Renovate config templating

Enable `renovate.configEnableHelmTpl` to use helm templates for generated renovate `config.json`.
```
what about this ? seems a better heading and description

2023-01-06 09:03 UTC, kvanzuijlen commented on charts/renovate/README.md.gotmpl
> +## renovate.configEnableHelmTpl
Sure!

2023-01-06 12:20 UTC, viceice commented on charts/renovate/README.md
> +## renovate.configEnableHelmTpl
needs an update too. 😉

2023-01-06 13:52 UTC, viceice approved these changes

2023-01-06 13:52 UTC, merged

2023-01-06 13:52 UTC, viceice commented
will be published with next renovate release