Deploy config containing secrets as Secret
renovatebot/helm-charts pull request #268
Opened 2023-01-11 19:33 UTC by kvanzuijlen

Added support for deploying the config.json as a secret

2023-01-11 19:37 UTC, viceice commented on charts/renovate/templates/configmap.yaml
> +{{- if .Values.renovate.configIsSecret }}
please move this above the metadata

2023-01-11 19:37 UTC, viceice commented on charts/renovate/templates/cronjob.yaml
> +                - |
avoid unrelated changed

2023-01-11 19:39 UTC, kvanzuijlen commented on charts/renovate/templates/cronjob.yaml
> +                - |
Sorry, triggerhappy IDE here, I'll roll back these changes!

2023-01-11 19:40 UTC, kvanzuijlen commented
@viceice Do you agree with conditionally creating a secret/configmap in the configmap.yaml? I think it keeps it better maintainable (no duplications) but it might be less readable.

2023-01-11 19:48 UTC, kvanzuijlen commented on charts/renovate/templates/configmap.yaml
> +{{- if .Values.renovate.configIsSecret }}
✅

2023-01-11 20:57 UTC, viceice commented
> @viceice Do you agree with conditionally creating a secret/configmap in the configmap.yaml? I think it keeps it better maintainable (no duplications) but it might be less readable.

we should probably rename the file to some more generic name

2023-01-11 21:10 UTC, kvanzuijlen commented
> > @viceice Do you agree with conditionally creating a secret/configmap in the configmap.yaml? I think it keeps it better maintainable (no duplications) but it might be less readable.
> 
> we should probably rename the file to some more generic name

My proposal would be to just call it `config.yaml`

2023-01-11 21:51 UTC, kvanzuijlen commented
@viceice I can't think of a way renaming the file (or the other changes in this PR) could be a breaking change. Do you see any potential problems?

2023-01-14 08:35 UTC, viceice requested changes

2023-01-14 08:35 UTC, viceice commented on charts/renovate/templates/config.yaml
> +metadata:
please move back before data section

2023-01-14 11:22 UTC, kvanzuijlen commented on charts/renovate/templates/config.yaml
> +metadata:
Moved it back

2023-01-14 14:59 UTC, viceice reviewed
thise seems like a better order to mee

2023-01-14 14:59 UTC, viceice commented on charts/renovate/templates/config.yaml
>  metadata:
```suggestion
{{- if .Values.renovate.configIsSecret }}
kind: Secret
type: Opaque
{{- else }}
kind: ConfigMap
{{- end }}
metadata:
```

2023-01-14 14:59 UTC, viceice commented on charts/renovate/templates/config.yaml
> +{{- end }}
```suggestion
{{- if .Values.renovate.configIsSecret }}
stringData:
{{- else }}
kind: ConfigMap
data:
{{- end }}
```

2023-01-14 18:44 UTC, viceice approved these changes

2023-01-14 18:44 UTC, merged

2023-01-14 18:44 UTC, viceice commented
will be published with next renovate release