Added support for Persistent Volume Claims for renovate cache
renovatebot/helm-charts pull request #273
Opened 2023-01-15 15:30 UTC by kvanzuijlen

Closes #163

2023-01-15 19:04 UTC, viceice requested changes

2023-01-15 19:04 UTC, viceice commented on charts/renovate/templates/pvc.yaml
> +  storageClassName: {{ .Values.renovate.persistence.cache.storageClass }}
should be optional and empty by default, as standard isn't available on all kubernetes platforms. if empty by default it uses the default kubernetes storage class which i would prefer for compabillity here.

2023-01-15 21:07 UTC, kvanzuijlen commented on charts/renovate/templates/pvc.yaml
> +  storageClassName: {{ .Values.renovate.persistence.cache.storageClass }}
Thanks, didn't know that! I'll make it conditional

2023-01-16 09:24 UTC, viceice approved these changes

2023-01-16 09:25 UTC, merged