allow slim config without dind
renovatebot/helm-charts pull request #283
Opened 2023-03-01 18:15 UTC by vquie

https://github.com/renovatebot/helm-charts/issues/281

Tested only via `helm template --debug .`. It renders as expected.

2023-03-01 20:49 UTC, viceice requested changes
doesn't fit the expecting results of the linked issue

2023-03-04 17:23 UTC, vquie commented
@viceice 
Can you please check again?

2023-03-05 08:28 UTC, viceice commented on .github/kubeval.sh
> +mkdir -p ./.bin
why this change?

2023-03-05 08:28 UTC, viceice commented on charts/renovate/values.yaml
> +  # -- Do not add `-slim` suffix to image tag
```suggestion
  # -- Add `-slim` suffix to image tag
```
i would prefer to reduce to `slim: false`.

I'll refactor the templates in one of next majors to simplify things.

2023-03-05 09:04 UTC, vquie commented on .github/kubeval.sh
> +mkdir -p ./.bin
To suppress errors if the folder already exists.

2023-03-05 09:09 UTC, vquie commented on charts/renovate/values.yaml
> +  # -- Do not add `-slim` suffix to image tag
I wanted to align this to the dind configuration. Both could be updated to `slim: true` though.
Changed it to `slim: true` now.

2023-03-05 13:28 UTC, viceice commented on charts/renovate/ci/ci-slim-without-dind.yaml
> +  enabled: true
```suggestion
slim: true
```

2023-03-05 13:28 UTC, viceice commented on charts/renovate/README.md
> +| slim | bool | `false` | Do not add `-slim` suffix to image tag |
```suggestion
| slim | bool | `false` | Add `-slim` suffix to image tag |
```

2023-03-07 10:25 UTC, viceice reviewed
i think we also should mention the binary source change

2023-03-07 10:25 UTC, viceice commented on charts/renovate/values.yaml
> +# -- Add `-slim` suffix to image tag
```suggestion
# -- Add `-slim` suffix to image tag and `binarySource=install`
```

2023-03-07 10:25 UTC, viceice commented on charts/renovate/README.md
> +| slim | bool | `false` | Add `-slim` suffix to image tag |
```suggestion
| slim | bool | `false` | Add `-slim` suffix to image tag and `binarySource=install` |
```

2023-03-07 10:27 UTC, viceice commented
Please add a slim section to the readme where we explain the `slim` flag in more detail.

eg: it uses the slim renovate image with `binarySource=install`

2023-03-07 19:02 UTC, viceice approved these changes

2023-03-07 19:59 UTC, merged

2023-03-07 20:01 UTC, viceice commented
will be released with next renovate version bump