Add option to configure registry mirror
renovatebot/helm-charts pull request #290
Opened 2023-04-02 11:47 UTC by Szpadel

Adds `dind.registryMirrors` array that can be used configure docker registry cache

Closes #277

2023-04-02 12:03 UTC, viceice requested changes
we'll remove dind soon. please use slim mode instead

2023-04-02 12:03 UTC, closed without merging

2023-04-02 18:00 UTC, Szpadel commented
@viceice is there somewhere instruction how configuration should be migrated? I tried removing find in one of self hosted installations working in gitlab-ci but it resulted in errors where external tools were needed.
 
If I understand correctly slim version does not have any tools installed? How that supposed to work?

2023-04-03 18:27 UTC, viceice commented
the slim image is installing tools on the fly since v35, like the docker binary source mode.

2023-04-03 18:29 UTC, viceice commented
just remove the dind values and set `slim=true`

2023-04-03 18:50 UTC, Szpadel commented
@viceice thanks for explaination, I wanted to test this but I realized that I use docker run inside postUpgradeTask. I use them to automatically bump versions for helm charts and docker containers. Using docker was required as some tools were missing in renovate container. Eg `jq`

How such scenario could be supported?

2023-04-04 08:11 UTC, viceice commented
you probably should extend the default renovate image and add your required stuff.