ci: stop testing on k8s v1.22 and v1.23
renovatebot/helm-charts pull request #304
Opened 2023-05-17 02:48 UTC by JamieMagee

A couple other fixes related to versions:

- Renovate `packageName` for `kubectl`
- Add endoflife.date links to the README
- Bump `kindest` tags

Closes #296

2023-05-17 03:45 UTC, viceice approved these changes

2023-05-17 03:46 UTC, viceice requested changes

2023-05-17 03:46 UTC, viceice commented on .devcontainer/Dockerfile
> +# renovate: datasource=github-tags depName=kubectl packageName=kubernetes/kubernetes
this is wrong

https://github.com/kubernetes/kubectl/tags

2023-05-17 03:52 UTC, JamieMagee commented on .devcontainer/Dockerfile
> +# renovate: datasource=github-tags depName=kubectl packageName=kubernetes/kubernetes
But `kubectl` is versioned alongside Kubernetes. The latest `kubectl` tags[^1] are [`kubernetes-1.27.1`][1] and [`v0.27.1`], and the download link for `kubectl` is

https://github.com/renovatebot/helm-charts/blob/04f4785407cb0bbf3e259c7693e7de2c1ed2eee0/.devcontainer/tools/kubectl.sh#L7

Which doesn't exist for `v0.27.1`.

I figured it was just easier to use the Kubernetes tags[^2] which do match to the download URL format.

[1]: https://github.com/kubernetes/kubectl/releases/tag/kubernetes-1.27.1
[2]: https://github.com/kubernetes/kubectl/releases/tag/v0.27.1
[^1]: https://github.com/kubernetes/kubectl/tags
[^2]: https://github.com/kubernetes/kubernetes/tags

2023-06-16 06:59 UTC, viceice commented on .devcontainer/Dockerfile
> +# renovate: datasource=github-tags depName=kubectl packageName=kubernetes/kubernetes
ok, extracted to separate commit

2023-06-16 07:08 UTC, viceice approved these changes

2023-06-16 07:08 UTC, merged