Test on k8s v1.19.0
renovatebot/helm-charts pull request #57
Opened 2020-08-27 20:09 UTC by JamieMagee

2020-08-27 20:17 UTC, viceice requested changes
We need push branches for renovate, otherwise automerge will it work nicely

2020-08-27 20:18 UTC, JamieMagee commented
> We need push branches for renovate, otherwise automerge will it work nicely

Is it not enough to have it just on PRs? Renovate always merges by PR in this repo.

2020-08-27 20:25 UTC, viceice commented
Then we need to remove prCreation, so PR is created immediately, otherwise renovate will wait 24h for succeed ci checks before opening PR.

2020-08-27 21:15 UTC, JamieMagee commented
Okay, I will re-instate the tests

2020-08-28 05:40 UTC, viceice commented on .github/workflows/ci.yaml
>        - 'charts/**'
```suggestion
```

2020-08-28 05:40 UTC, viceice commented on .github/kubeval.sh
> -set -euo pipefail
Why this change?

2020-08-28 07:36 UTC, merged