chore: initial github codespace configuration
renovatebot/helm-charts pull request #79
Opened 2020-11-05 12:39 UTC by JamieMagee

Builds on much of the work done by @viceice for creating dependency toolchain docker images and extends this to install development toolchains as well. This is a draft PR, because I want to get feedback on the approach, before going any further.

Closes #75

2020-11-05 12:47 UTC, viceice reviewed
I can't really test it, as i've no access to code spaces 🙃

2020-11-05 12:47 UTC, viceice commented on .devcontainer/Dockerfile
> +# COPY --from=helm /usr/local/helm/${HELM_VERSION}/helm /usr/local/bin/helm
```suggestion
# renovate: datasource=github-releases depName=helm/helm
ARG HELM_VERSION=3.4.0
RUN install-tool helm
```

needs renovate config change:
```json
"packageRules": [
    {
      "packageNames": ["helm/helm"],
      "extractVersion": "^v(?<version>.*)$"
    }
  ]
```

2020-11-05 12:47 UTC, viceice commented on .devcontainer/tools/kubectl.sh
> +curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v"$KUBECTL_VERSION"/bin/linux/amd64/kubectl
```suggestion
curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
```

2020-11-05 12:47 UTC, viceice commented on .devcontainer/tools/kubectl.sh
> +chmod +x /usr/local/bin/kubectl
```suggestion
chmod +x /usr/local/bin/kubectl
kubectl version --client=true
```

2020-11-05 12:50 UTC, JamieMagee commented
> I can't really test it, as i've no access to code spaces

You can test locally using [vscode containers](https://code.visualstudio.com/docs/remote/containers). It's exactly the same technology, just for GitHub codespaces vscode is running in your browser.

2020-11-05 13:07 UTC, viceice commented
So I think we need the helm test tools to lint /test locally

2020-11-05 13:19 UTC, JamieMagee commented
> So I think we need the helm test tools to lint /test locally

I agree, but I didn't want to put the effort in to package them before getting your opinion on this approach. What do you think about reusing your docker buildpack work for dev containers here, and potentially in other repositories in the renovatebot organisation?

2020-11-05 13:59 UTC, viceice commented
I like that idea. Maybe we should move the build to our ci and publish to ghcr. So the user doesn't need to / wait for rebuild the container every time. 🤔

2020-11-06 08:51 UTC, JamieMagee commented on .devcontainer/tools/kubectl.sh
> +curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v"$KUBECTL_VERSION"/bin/linux/amd64/kubectl
Is this correct? Shellcheck doesn't seem to agree: https://github.com/koalaman/shellcheck/wiki/SC2086

2020-11-06 09:57 UTC, viceice commented on .devcontainer/tools/kubectl.sh
> +curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v"$KUBECTL_VERSION"/bin/linux/amd64/kubectl
Ok, i see, so quoted the full url. 🙃

2020-12-07 16:16 UTC, viceice requested changes

2020-12-07 16:16 UTC, viceice commented on .devcontainer/tools/chart_testing.sh
> +#!/usr/bin/env bash
Why not using `chart-testing` as name? Or better `helm-chart-testing`? 🤔

2020-12-07 16:16 UTC, viceice commented on .devcontainer/Dockerfile
> +RUN install-tool helm_docs
Add newline 🙃

2020-12-07 16:19 UTC, viceice commented on .devcontainer/Dockerfile
> +FROM renovate/buildpack:2
```suggestion
FROM renovate/buildpack:2-focal
```
Use ubuntu focal to have newer python.

2020-12-08 11:47 UTC, JamieMagee commented on .devcontainer/tools/chart_testing.sh
> +#!/usr/bin/env bash
I hit some issues with trying to import this script while using `-`. `_` worked fine though.

2020-12-16 10:55 UTC, viceice commented
ref renovatebot/docker-buildpack#88

2020-12-16 21:33 UTC, viceice commented on .devcontainer/tools/chart_testing.sh
> +#!/usr/bin/env bash
Was hit by the same issue [here](https://github.com/visualon/docker-images/blob/3ce332d1580911efb3b7128ea8744f962ecc7cbc/docker/github-runner/Dockerfile#L31) 😛 

So simply fixed it in renovatebot/docker-buildpack#88 🙃

2020-12-16 21:34 UTC, viceice commented on .devcontainer/tools/kubectl.sh
> +curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v"$KUBECTL_VERSION"/bin/linux/amd64/kubectl
I'm nor sure if we even need the escape, as we check the value right before 🤔

2020-12-30 20:29 UTC, JamieMagee commented
I've got this (mostly working) now. The 2 missing pieces are:
1. `helm` is not added to `PATH` correctly (but it is installed correctly)
2. Connection to the host `docker.sock` is not initialised correctly

Even with the issues above, I still think this is useful, and they can be addressed later.

2020-12-30 21:09 UTC, viceice reviewed
Strange, helm should be installed as `/usr/local/bin/helm` maybe something is overriding the path with wrong values

2020-12-30 21:09 UTC, viceice commented on .devcontainer/devcontainer.json
> +  "mounts": ["source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"],
```suggestion
  "mounts": ["source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind"],
```

Why changed path?

2020-12-30 21:09 UTC, viceice commented on renovate.json
>      }
```suggestion
    {
      "packageNames": ["helm/helm", "kubernetes/kubectl"],
      "extractVersion": "^v(?<version>.*)$"
    }
```

Simplify 🙃

2020-12-30 21:41 UTC, JamieMagee commented on .devcontainer/devcontainer.json
> +  "mounts": ["source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind"],
It was part of the guide [here](https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/docker.md). I couldn't get it to work, due to permissions, so it's a moot point.

2020-12-30 21:43 UTC, JamieMagee commented
Helm is installed to `/usr/local/helm/3.4.0`

2021-01-03 19:38 UTC, merged